import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { jaJP } from "@clerk/localizations";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <ClerkProvider localization={jaJP}>
        <html lang="ja">
        <body className={inter.className}>
        <main className="mx-auto flex min-h-screen max-w-5xl flex-col place-content-center justify-between md:p-12">
          {children}
        </main>
        </body>
        </html>
      </ClerkProvider>
  )
}
